CREATE TABLE user_info (
	email VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	dob VARCHAR(20) NOT NULL,
	country_code VARCHAR(3) NOT NULL
);

CREATE TABLE user_token (
    email VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE
);