CREATE TABLE user_info (
	id MEDIUMINT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	dob VARCHAR(20) NOT NULL,
	country_code VARCHAR(3) NOT NULL,
	topics VARCHAR(255) NOT NULL
);

CREATE TABLE user_token (
	id MEDIUMINT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
    user_id MEDIUMINT NOT NULL UNIQUE,
    token VARCHAR(600) NOT NULL UNIQUE KEY,
    FOREIGN KEY (user_id) REFERENCES user_info(id) ON DELETE CASCADE
);
