web:
  build: .
  environment:
    - RACK_ENV=development
    - AUTH_PRIV_KEY=/app/test-resources/pav_auth_privkey.pem
    - AUTH_PRIV_KEY_PWD=password
    - AUTH_PUB_KEY=/app/test-resources/pav_auth_pubkey.pem
    - AUTH_PUB_KEY_PWD=password
    - PORT=8080
    - SSLPORT=8443
    - LEIN_ROOT=1
    - MYSQL_DATABASE=pav_user
    - MYSQL_HOST=pav-user-dev.cohs9sc8kicp.us-west-2.rds.amazonaws.com
    - MYSQL_PORT=3306
    - MYSQL_USER=pav_user
    - MYSQL_PASSWORD=pav_user
  ports:
    - 8080:8080
    - 8443:8443