web:
  build: .
  environment:
    - RACK_ENV=development
    - NEO_USERNAME=neo4j
    - NEO_PASSWORD=password
    - AUTH_PRIV_KEY=test-resources/pav_auth_privkey.pem
    - AUTH_PRIV_KEY_PWD=password
    - PORT=8080
    - SSLPORT=8443
    - LEIN_ROOT=1
  ports:
    - 8080:8080
    - 8443:8443
  volumes:
    - .:/app
  links:
    - neo4j
    - redis
redis:
  image: redis
neo4j:
  environment:
    - NEO4J_AUTH=none
  image: tpires/neo4j